import { Metric } from './types/metric';

export const RebuiltMetrics: Record<string, Metric> = {
  TotalPoints: {
    id: 'total_points',
    name: 'Total Points',
    type: 'NUMBER',
    unit: 'points',
    category: 'SCORING',
    year: 2026,
    op: 'points',
    config: {
      pointBonuses: { includeAutoClimb: true, includeEndgameClimb: true, applyAccuracy: true },
    },
  },
  AutoPoints: {
    id: 'auto_points',
    name: 'Auto Points',
    type: 'NUMBER',
    unit: 'points',
    category: 'AUTONOMOUS',
    year: 2026,
    op: 'points',
    config: { pointBonuses: { includeAutoClimb: true, applyAccuracy: true } },
  },
  TeleopPoints: {
    id: 'teleop_points',
    name: 'Teleop Points',
    type: 'NUMBER',
    unit: 'points',
    category: 'TELEOP',
    year: 2026,
    op: 'points',
    config: { pointBonuses: { applyAccuracy: true } },
  },
  ScoringRate: {
    id: 'scoring_rate',
    name: 'Scoring Rate',
    type: 'NUMBER',
    unit: 'scores/min',
    category: 'SCORING',
    year: 2026,
    op: 'rate',
    config: { pairedAction: 'SCORING' },
  },
  Accuracy: {
    id: 'accuracy',
    name: 'Accuracy',
    type: 'NUMBER',
    unit: '%',
    category: 'SCORING',
    year: 2026,
    op: 'valueMap',
    report: 'accuracy',
    config: { valueMap: { 0: 25, 1: 55, 2: 65, 3: 75, 4: 85, 5: 95 } },
  },
  VolleysPerMatch: {
    id: 'volleys_per_match',
    name: 'Volleys Per Match',
    type: 'NUMBER',
    unit: 'volleys',
    category: 'SCORING',
    year: 2026,
    op: 'eventCount',
    event: ['START_SCORING'],
  },
  TotalFuelOutputted: {
    id: 'total_fuel_outputted',
    name: 'Total Fuel Outputted',
    type: 'NUMBER',
    unit: 'balls',
    category: 'SCORING',
    year: 2026,
    op: 'eventSum',
    event: ['STOP_SCORING', 'STOP_FEEDING'],
    config: { useQuantity: true },
  },
  TotalBallThroughput: {
    id: 'total_ball_throughput',
    name: 'Total Ball Throughput',
    type: 'NUMBER',
    unit: 'balls',
    category: 'SCORING',
    year: 2026,
    op: 'eventSum',
    event: ['STOP_SCORING'],
    config: { useQuantity: true },
  },
  ScoresWhileMoving: {
    id: 'scores_while_moving',
    name: 'Scores While Moving',
    type: 'BOOLEAN',
    unit: '%',
    category: 'SCORING',
    year: 2026,
    op: 'reportRatio',
    report: 'scoresWhileMoving',
  },
  IntakeType: {
    id: 'intake_type',
    name: 'Intake Type',
    type: 'ENUM',
    category: 'SCORING',
    year: 2026,
    op: 'reportMode',
    report: 'intakeType',
  },

  AutoClimb: {
    id: 'auto_climb',
    name: 'Auto Climb',
    type: 'ENUM',
    category: 'AUTONOMOUS',
    year: 2026,
    op: 'reportMode',
    report: 'autoClimb',
  },
  AutoClimbStartTime: {
    id: 'auto_climb_start_time',
    name: 'Auto Climb Start Time',
    type: 'TIME',
    unit: 'seconds',
    category: 'AUTONOMOUS',
    year: 2026,
    op: 'climbTime',
    config: { climbLevel: 'auto' },
  },

  EndgameClimb: {
    id: 'endgame_climb',
    name: 'Endgame Climb',
    type: 'ENUM',
    category: 'ENDGAME',
    year: 2026,
    op: 'reportMode',
    report: 'endgameClimb',
  },
  ClimbSuccessRate: {
    id: 'climb_success_rate',
    name: 'Climb Success Rate',
    type: 'BOOLEAN',
    unit: '%',
    category: 'ENDGAME',
    year: 2026,
    op: 'reportRatio',
    report: 'endgameClimb',
    config: { trueValues: ['L1', 'L2', 'L3'], excludeValues: ['NOT_ATTEMPTED'] },
  },
  L1StartTime: {
    id: 'l1_start_time',
    name: 'L1 Start Time',
    type: 'TIME',
    unit: 'seconds',
    category: 'ENDGAME',
    year: 2026,
    op: 'climbTime',
    config: { climbLevel: 'L1' },
  },
  L2StartTime: {
    id: 'l2_start_time',
    name: 'L2 Start Time',
    type: 'TIME',
    unit: 'seconds',
    category: 'ENDGAME',
    year: 2026,
    op: 'climbTime',
    config: { climbLevel: 'L2' },
  },
  L3StartTime: {
    id: 'l3_start_time',
    name: 'L3 Start Time',
    type: 'TIME',
    unit: 'seconds',
    category: 'ENDGAME',
    year: 2026,
    op: 'climbTime',
    config: { climbLevel: 'L3' },
  },
  Beached: {
    id: 'beached',
    name: 'Beached',
    type: 'ENUM',
    category: 'ENDGAME',
    year: 2026,
    op: 'reportMode',
    report: 'beached',
  },

  TotalDefenseTime: {
    id: 'total_defense_time',
    name: 'Total Defense Time',
    type: 'TIME',
    unit: 'seconds',
    category: 'DEFENSE',
    year: 2026,
    op: 'pairedDuration',
    config: { dualPaired: ['DEFENDING', 'CAMPING'] },
  },
  ContactDefenseTime: {
    id: 'contact_defense_time',
    name: 'Contact Defense Time',
    type: 'TIME',
    unit: 'seconds',
    category: 'DEFENSE',
    year: 2026,
    op: 'pairedDuration',
    config: { pairedAction: 'DEFENDING' },
  },
  CampingDefenseTime: {
    id: 'camping_defense_time',
    name: 'Camping Defense Time',
    type: 'TIME',
    unit: 'seconds',
    category: 'DEFENSE',
    year: 2026,
    op: 'pairedDuration',
    config: { pairedAction: 'CAMPING' },
  },
  DefenseEffectiveness: {
    id: 'defense_effectiveness',
    name: 'Defense Effectiveness',
    type: 'NUMBER',
    unit: 'rating',
    category: 'DEFENSE',
    year: 2026,
    op: 'reportAvg',
    report: 'defenseEffectiveness',
  },
  Disrupts: {
    id: 'disrupts',
    name: 'Disrupts',
    type: 'BOOLEAN',
    unit: '%',
    category: 'DEFENSE',
    year: 2026,
    op: 'reportRatio',
    report: 'disrupts',
  },

  FeedingTime: {
    id: 'feeding_time',
    name: 'Feeding Time',
    type: 'TIME',
    unit: 'seconds',
    category: 'FEEDING',
    year: 2026,
    op: 'pairedDuration',
    config: { pairedAction: 'FEEDING' },
  },
  FeedingRate: {
    id: 'feeding_rate',
    name: 'Feeding Rate',
    type: 'NUMBER',
    unit: 'balls/min',
    category: 'FEEDING',
    year: 2026,
    op: 'rate',
    config: { pairedAction: 'FEEDING', useQuantity: true },
  },
  FeedsPerMatch: {
    id: 'feeds_per_match',
    name: 'Feeds Per Match',
    type: 'NUMBER',
    unit: 'feeds',
    category: 'FEEDING',
    year: 2026,
    op: 'eventCount',
    event: ['START_FEEDING'],
  },
  TotalBallsFed: {
    id: 'total_balls_fed',
    name: 'Total Balls Fed',
    type: 'NUMBER',
    unit: 'balls',
    category: 'FEEDING',
    year: 2026,
    op: 'eventSum',
    event: ['STOP_FEEDING'],
    config: { useQuantity: true },
  },
  FeederType: {
    id: 'feeder_type',
    name: 'Feeder Type',
    type: 'ENUM',
    category: 'FEEDING',
    year: 2026,
    op: 'reportMode',
    report: 'feederTypes',
  },

  DriverAbility: {
    id: 'driver_ability',
    name: 'Driver Ability',
    type: 'NUMBER',
    unit: 'rating',
    category: 'DRIVER',
    year: 2026,
    op: 'reportAvg',
    report: 'driverAbility',
  },

  RobotRole: {
    id: 'robot_role',
    name: 'Robot Role',
    type: 'ENUM',
    category: 'OTHER',
    year: 2026,
    op: 'reportMode',
    report: 'robotRoles',
  },
  FieldTraversal: {
    id: 'field_traversal',
    name: 'Field Traversal',
    type: 'ENUM',
    category: 'TELEOP',
    year: 2026,
    op: 'reportMode',
    report: 'fieldTraversal',
  },

  OutpostIntakes: {
    id: 'outpost_intakes',
    name: 'Outpost Intakes',
    type: 'NUMBER',
    unit: 'intakes',
    category: 'TELEOP',
    year: 2026,
    op: 'eventCount',
    event: ['INTAKE'],
    config: { position: 'OUTPOST' },
  },
};
